### ISSUE TITLE
Can't run Storybook

### ISSUE THREAD

**Issue by ndorfin** [MathewBoyles/locations-of-interest#3]
I tried to launch Storybook using the provided node script:

```bash
npm run storybook
```

It fails in my development environment, complaining about duplicate presets/plugins to do with `babel-loader`.
[I found a fix for that](https://github.com/storybookjs/storybook/issues/12802#issuecomment-711143865), so I:

- deleted the `@storybook/preset-typescript` dependency, and
- removed it from Storybook's config in `/.storybook/main.js`
- reinstalled dependencies and 
- tried again.

The server would start normally, but any requests for `http://localhost:9009` would result in a 404.

What am I missing?

Thanks!
-S

**Comment by MathewBoyles** [comment]
Storybook wasn't setup fully when the template was copied. This has been resolved in the following commits and have added some basic stories.

https://github.com/MathewBoyles/locations-of-interest/commit/fadd4b13b0d0eca6fc45f76d4aa5ab38f0dbf1d7
https://github.com/MathewBoyles/locations-of-interest/commit/ca5877d8b7b06f25ce3df96647f188fea2ad0478

**Comment by ndorfin** [comment]
Ah, wow, thanks @MathewBoyles 
I thought I had some sort of local environment issue! 
Will check it out :)
